### ISSUE TITLE
Is it possible find and replace for multiple notes

### ISSUE THREAD

**Issue by wenlzhang** [TClark1011/obsidian-find-and-replace-in-selection#1]
Is it possible to find and replace in multiple notes, instead of just one?

**Comment by TClark1011** [comment]
The scope of this plugin is just for a find/replace within your current selection. I am aware that you can have highlights across multiple notes via plugins like Sliding Panes, but as far as I am aware the obsidian API only allows access to the text selected in the currently active note, unfortunately.

**Comment by wenlzhang** [comment]
Thanks for the information. That's indeed unfortunate news. Maybe I can open the vault in VS Code and make such changes there with the following plugin:
[NomarCub/obsidian-open-vscode: Open vault in VSCode button for Obsidian.md](https://github.com/NomarCub/obsidian-open-vscode)

**Comment by TClark1011** [comment]
That should work, I have used VSCode to do that myself and it worked just fine
