### ISSUE TITLE
Replacing breaklines

### ISSUE THREAD

**Issue by ghost** [TClark1011/obsidian-find-and-replace-in-selection#2]
Hi !
Thanks for the plugin, really love it !

Do you know if there is any way that we could replace breaklines for any characters ?
I wanted to replace copied pdf text breaklines by searching for "\n" and replacing them with spaces but it didn't work.

Is there any way to do that in the plugin and if not, do you believe you'll implement this feature ?

Thanks a lot !

**Comment by TClark1011** [comment]
The plugin doesn't currently support this but its definitely worth adding, I'll look into it this weekend.

**Comment by TClark1011** [comment]
@Animaly0 I just published the update for this. Once you upgrade to version 1.1.0 you can use '\n' in the 'Find' field to replace line breaks

**Comment by ghost** [comment]
Thanks a lot, that's life changing <3
